In [1]:
# 001_задание

In [2]:
import numpy as np

In [3]:
my_array = [[1, 6],
           [2, 8],
           [3, 11],
           [3, 10],
           [1, 7]]

In [9]:
a = np.array(my_array)
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [10]:
mean_a = np.mean(my_ndarray, axis=0)
mean_a

array([2. , 8.4])

In [ ]:
# 002_задание 

In [19]:
a_centered = a - mean_a
a_centered 

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [20]:
# 003_задание

In [28]:
a_centered[:, 0]

array([-1.,  0.,  1.,  1., -1.])

In [29]:
a_centered_sp = a_centered[:, 0].dot(a_centered[:, 1])
a_centered_sp

8.0

In [31]:
a_centered.shape

(5, 2)

In [33]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0